### ISSUE TITLE
Cross-migration transaction support

### ISSUE THREAD

**Issue by venantius** [weavejester/ragtime#100]
I'm curious as to whether there's a way to wrap ragtime's migrations in a transaction block. 

To be clear, I'm not talking about per-migration transactions (i.e., begin - migration - transaction), but rather a cross-migration transaction block:
begin
migration1
migration2
migration3
...
commit

I'm asking because I'm looking at whether I can hastily run all migrations on my test database, execute a test, and then return the state of the world to 0 before doing it all again for each test. 

I've been trying to do this in a way that plays nicely with Korma but my guess is that ragtime is handling its own DB connection and so they're not actually sharing the transaction block. Any thoughts on how to handle this?

**Comment by weavejester** [comment]
The `ragtime.jdbc/sql-database` function takes a [db-spec](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/get-connection), which can contain a raw connection instead of a database URL. So you could do something like:

```clojure
(clojure.java.jdbc/with-db-connection [t db-spec]
  (let [datastore (ragtime.jdbc/sql-database {:connection t})]
    ...))
```

**Comment by venantius** [comment]
I unfortunately realized this after filing the issue. Thanks for the quick response, though, and sorry for the noise :)

**Comment by weavejester** [comment]
No problem!
