### ISSUE TITLE
What fields db-spec should have

### ISSUE THREAD

**Issue by arichiardi** [weavejester/ragtime#102]
Sorry for the silly question, but I am using the same map as `boot-ragtime` uses and I get:

`db-spec {:adapter :postgresql, :jdbc-url , :username
   , :password , :init-size 1, :min-idle 1, :max-idle 4, :max-active 32} is missing
   a required parameter`

**Comment by weavejester** [comment]
Ragtime uses the standard clojure.java.jdbc library. You can see the list of options for the db-spec in the [get-connection](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/get-connection) docstring.

**Comment by arichiardi** [comment]
Oh thanks! I will PR the README ok?

**Comment by arichiardi** [comment]
Actually I PR-ed the `Getting Started`, thanks a lot for the support!

**Comment by weavejester** [comment]
I was just about to suggest that. Thanks!

**Comment by arichiardi** [comment]
Thank you!
