### ISSUE TITLE
Using resources for migration files under windows causes bad migration ID

### ISSUE THREAD

**Issue by cshclm** [weavejester/ragtime#103]
For migration files provided by Java resources under MS Windows, the absolute pathname to the migration file is stored as the migration ID.

---

The path basename is used as the migration ID for .sql files, where the basename is determined using a regexp using OS-specific separators.

``` clojure
(let [pattern (re-pattern (str "([^\\" File/separator "]*)\\" File/separator "?$"))]
  (defn- basename [file]
    (second (re-find pattern (str file)))))
```

However Java resources always use forward-slash ("/") as the path separator, making the basename regexp invalid for resources under Windows.

The result is an ID of the form `jar:file:/path/to/file.jar!/migrations/001-mymigration`, instead of `001-mymigration` as expected.  This introduces two problems:
1. changes to the path of the jar or resource introduce migration conflicts,
2. the database becomes tied to the platform

**Comment by ulsa** [comment]
I've got the same problem. Any suggestions on how to resolve this?

**Comment by cshclm** [comment]
I worked around it by rebinding the problem function.

```clojure
(let [pattern (re-pattern (str "([^\\/]*)\\/?$"))]
  (defn- -resource-basename
    [file]
    (second (re-find pattern (str file)))))
(intern 'ragtime.jdbc 'basename #'-resource-basename)
```

**Comment by weavejester** [comment]
Patches for this issue are welcome.

**Comment by adamtornhill** [comment]
The rebinding by @cshclm works fine, but only when present in the first version of a program; It still fails when you have an existing database on Windows that you need to migrate because the absolute paths are already stored as migration IDs.

I solved it by rebinding one more function, `migrate-all`,  to strip away the paths from the existing/stored migration IDs. Here's my complete patch:

```clojure
    (let [pattern (re-pattern (str "([^\\/]*)\\/?$"))]
      (defn- -resource-basename
        [file]
        (second (re-find pattern (str file)))))
     (intern 'ragtime.jdbc 'basename #'-resource-basename)

    (defn- -migrate-without-file-names
      ([store index migrations]
        (-migrate-without-file-names store index migrations ragtime.strategy/raise-error))
      ([store index migrations strategy]
        (let [index   (ragtime.core/into-index index migrations)
               stored-applied (ragtime.protocols/applied-migration-ids store)
               applied (map -resource-basename stored-applied)] ; strip the JAR file name on Windows
           (doseq [[action migration-id] (strategy applied (map ragtime.protocols/id migrations))]
             (case action
               :migrate  (ragtime.core/migrate store (index migration-id))
               :rollback (ragtime.core/rollback store (index migration-id)))))))
     (intern 'ragtime.core 'migrate-all #'-migrate-without-file-names)
```

**Comment by jconti** [comment]
I just hit this issue too. Rather than patch the library's code (at runtime) for Windows, would it be possible to simply re-implement the Migration protocol's (id) method for Windows?

**Comment by weavejester** [comment]
As I said before, I'm happy to accept a PR that solves this issue. I don't use Clojure under Windows, so this isn't something I can easily test myself.

**Comment by jconti** [comment]
My pleasure.  Ring has been very very good to me, BTW.  Your work is much appreciated.

I think [this pull request](https://github.com/weavejester/ragtime/pull/121) will do it.

**Comment by jconti** [comment]
My current workaround looks like this:
```
(defn load-migrations-for [db-name]
  ;; todo: remove work around for https://github.com/weavejester/ragtime/issues/103
  ; (ragtime.jdbc/load-resources (str "migrations/" db-name))
  (->> (str "migrations/" db-name)
       (resauce.core/resource-dir)
       (map clojure.java.io/as-file)
       (#'ragtime.jdbc/load-all-files)))
```
