### ISSUE TITLE
Deprecation alert in SQL migrations

### ISSUE THREAD

**Issue by malfario** [weavejester/ragtime#105]
SQL migrations print a deprecation alert:

```
DEPRECATED: unrolled column specs / key/value arguments to create-table-ddl
DEPRECATED: unrolled key/value arguments to query
```

From release notes for clojure.java.jdbc 0.5.6 at <https://github.com/clojure/java.jdbc>:

>
create-table-ddl now expects the column specs to be wrapped in a single vector and no longer needs the :options delimiter to specify the options map JDBC-120.
If column specs are not wrapped in a vector, you will get a "DEPRECATED" warning printed to the console.

**Comment by weavejester** [comment]
Which version of Ragtime are you using? This should be fixed in 0.6.0.

**Comment by malfario** [comment]
Sorry, didn't notice the version spec in the readme; I'm using version 0.5.2 as per instructions from the *Getting started* guide.

Upgrading to 0.6.0 indeed fixes the issue.

Thanks!

**Comment by malfario** [comment]
I hope you don't mind I've updated the version spec in the *Getting Started* wiki page. Cheers!

**Comment by weavejester** [comment]
Thanks for updating it! That was something that I forgot to do last release.

**Comment by malfario** [comment]
I'm glad I could help, thank you for your great work!
