### ISSUE TITLE
Calling ragtime.repl/rollback with a non-existant migration has different effects, depending on the current database state

### ISSUE THREAD

**Issue by alzadude** [weavejester/ragtime#109]
Hi there,

I'm seeing the following different effects when calling `ragtime.repl/rollback` with a non-existant migration, which from my basic analysis seems to depend on the current database state of migrations, and/or whether there are existing migrations available to apply.

I just wanted to check my understanding:
1. When calling with database state at 001-first-migration, if 002-second-migration is available via `ragtime.jdbc/load-resources`, a call to `ragtime.repl/rollback` with migration `non-existant-id` results in `Exception Could not find migration 'non-existant-id' in database  ragtime.core/rollback-to (core.clj:66)` (to me, this exception makes sense.)
2. When calling with database state at 002-second-migration, with no more migrations available via `ragtime.jdbc/load-resources`, a call to `ragtime.repl/rollback` with migration `non-existant-id` results in a rollback of all migrations, and the function returns `nil`. (this I do not understand.)

Should I expect these different effects in the case of a non-existant migration?

I'm using version 0.6.1.

Thanks :)

**Comment by weavejester** [comment]
Sorry for the late reply. The (2) scenario you mention shouldn't happen. The rollback function takes all the applied migrations and searches through them to find the id you want to roll back to. If it can't find that id, it raises an error.

**Comment by weavejester** [comment]
Is there an example project you can provide where this error happens consistently, or is repeatable in some way?

**Comment by welovelain** [comment]
I happened to meet the same problem. (also I don't use jdbc, but working with cassandra)

Behavior:
1.
initial state: empty db
> migrate -> migrates all
> rollback nonexistentid -> rollback everything

2.
initial state: empty db
> rollback nonexistentid -> "couldn't find migration "nonexistentid" in database

3.
initial state: empty db
> migrate -> migrates all
> (add some more migration files)
> rollback nonexistentid -> rollbacks everything

I think something may be wrong with this piece of code in core.clj:

(defn rollback-to
  "Rollback to a specific migration ID, using the supplied migration index."
  [store index migration-id]
  (let [migrations (applied-migrations store index)
        discards   (->> (reverse migrations)
                        (take-while #(not= (p/id %) migration-id)))]
    (if (= discards migrations)
      (throw (Exception. (str "Could not find migration '" migration-id "' in database")))
      (doseq [migration discards]
        (rollback store migration)))))

For ex, maybe migrations are not equal to (reverse migrations). But I'm not so good at Clojure, so I don't know. Anyway, this can hurt db seriously. If you need some more information, I'd be glad to share

**Comment by weavejester** [comment]
Yes, as you point out, it looks like the condition check is wrong. Reversing the discards or even just comparing a count should work instead.

I'll put together a fix, unless you want to beat me to it.

**Comment by welovelain** [comment]
Sure, I'll send pull request soon, thanks for reply
