### ISSUE TITLE
JDBC Migration Ordering

### ISSUE THREAD

**Issue by xsc** [weavejester/ragtime#111]
I'm having a use case where I want to generate a JDBC migration from an EDN map that's stored together with the other, plain SQL migrations. For this, I implement `ragtime.jdbc/load-files` for the `.special` extension, resulting in the following files being available:

``` clojure
000-setup-tables.up.sql
000-setup-tables.down.sql
001-setup-specials.special
002-setup-more-stuff.up.sql
002-setup-more-stuff.down.sql
```

Currently, ragtime runs these in an "unexpected" order (`000`, `002`, `001`) since the JDBC migration logic sorts them first, then groups them by file extension, then loads the contents and concatenates the results. I can fix this in my code using:

``` clojure
(sort-by :id (ragtime.jdbc/load-resources "migrations"))
```

Now, my question: should ragtime core (or at least the JDBC part) maybe already sort by `ragtime.protocols/id` (or `:id`) itself? If yes, I'd be happy to supply a patch.

**Comment by weavejester** [comment]
Ragtime core shouldn't sort by ID, but it's reasonable for the JDBC loader to, I think. The commit you added seems fine for inclusion.
