### ISSUE TITLE
Optional Down Migrations?

### ISSUE THREAD

**Issue by citizenparker** [weavejester/ragtime#12]
Just checking before I submit a pull request - would you accept a patch to add optional down migrations in ragtime.sql.files? In production apps, I never find the concept of rollbacks feasible but yet have to create empty down migrations to get Ragtime to run.

**Comment by drusellers** [comment]
:+1:

**Comment by piranha** [comment]
:+1:

**Comment by ludwinas** [comment]
:+1:

**Comment by drusellers** [comment]
@weavejester is this something you would support?

**Comment by weavejester** [comment]
I think this behavior might already be supported, at least in JDBC migrations.

**Comment by drusellers** [comment]
Doesn't appear to be. :/ 

```
$ lein ragtime migrate
Exception in thread "main" java.lang.AssertionError: Assert failed: Incomplete migrations found. Please provide up and down migration files for 0001_test_table
(empty? incomplete-files)
```

##From project.clj
```
:dependencies [
[ragtime/ragtime.sql.files "0.3.9"]
]
  :plugins [
            [ragtime/ragtime.lein "0.3.9"]
          ]
  :ragtime {
    :migrations ragtime.sql.files/migrations
    :database "jdbc:postgresql://localhost:5432/egg?user=egg"
  }
```

**Comment by weavejester** [comment]
You're using an older version of Ragtime. Try upgrading to the latest one.

**Comment by drusellers** [comment]
> And then the clouds parted and the light of reason and logic revealed the way forward

Oh, wow!! I love the new syntax and approach and as you thought, the new behavior is indeed there. Thank you. :) I would consider the issue closed myself.

**Comment by weavejester** [comment]
It's encouraging to know that you feel the new versions are an improvement over the old. There have been a few breaking changes, after all.

I'll mark this issue as fixed.
