### ISSUE TITLE
Migration strategy for continuous delivery

### ISSUE THREAD

**Issue by dlebrero** [weavejester/ragtime#128]
We have started doing blue/green deployments in one of our projects, which means that we have two versions of an application running at the same time against the same database.

When the new version of the application starts, the migrations for the new version are applied correctly, but if the old version of the application is restarted (for whatever reason), the old version finds the new migrations (which it doesn't know anything about) in the DB and refuses to start.

We implemented a [ignore-any-future-migrations strategy](https://github.com/akvo/akvo-lumen/blob/122a5c22cf3b7305117d09b1b6f8a949a220c1a9/backend/src/akvo/lumen/migrate.clj#L19) for this case. Test are [here](https://github.com/akvo/akvo-lumen/blob/2d0e6e00bed2f17c1321ad36377091f540f0b604/backend/test/akvo/lumen/migrate_test.clj#L5).

We were wondering if a PR to incorporate this strategy to ragtime would be interesting.

**Comment by weavejester** [comment]
Yes, I think a PR would perfectly acceptable, if you have time to put one together. It seems a reasonable use-case, and strategies are isolated pure functions, so I have a low barrier to adding new ones, so long as they have at least some justification.

**Comment by dlebrero** [comment]
Created PR #129 

Will update also the doc at https://github.com/weavejester/ragtime/wiki/Concepts once the PR has been merged

**Comment by dlebrero** [comment]
Updated the doc at https://github.com/weavejester/ragtime/wiki/Concepts
