### ISSUE TITLE
Programmatic Migrations?

### ISSUE THREAD

**Issue by citizenparker** [weavejester/ragtime#13]
Is there an officially supported way to run migrations programmatically? We have been using   ```ragtime.main#migrate``` to do the trick which is easy enough. However, the method is totally undocumented and so I'm unsure whether we're relying on Ragtime implementation details to make this work, or if this method is a contract to the outside world.

If this is by design, would you accept a documentation-only pull request to clarify the arguments and usage?

(If you're curious why we do this, we don't store our configuration in Leiningen so the ```lein ragtime *``` commands don't do much for us.)

**Comment by weavejester** [comment]
Fixed by the version 0.4.0 redesign and the `ragtime.repl` namespace.
