### ISSUE TITLE
Consider changing the SQL separator to support MySQL users for the better

### ISSUE THREAD

**Issue by dharrigan** [weavejester/ragtime#159]
Hi,

Presently, ragtime looks for `--;;` within a sql file to split up statements (as defined [here](https://github.com/weavejester/ragtime/blob/091a7a7e09e6dc1011c1d3805f3c8ae0e51f199c/next-jdbc/src/ragtime/next_jdbc.clj#L166) and [here](https://github.com/weavejester/ragtime/blob/091a7a7e09e6dc1011c1d3805f3c8ae0e51f199c/jdbc/src/ragtime/jdbc.clj#L131).)

However, for MySQL, the comment `--;;` is invalid and flags an error in the SQL when attempting to execute a perfectly valid SQL file, as MySQL requires that a `--` is followed either by a space or a control character. This is detailed in the MySQL reference manual [here](https://dev.mysql.com/doc/refman/8.0/en/ansi-diff-comments.html). This does not apply to other databases, such as PostgreSQL or Oracle which both treat a comment as a line starting with `--` all the way until the end of the line.

Thus, when loading a SQL file into tools such as DataGrip, the file is littered with errors as the parser (following MySQL parsing rules) correctly flags `--;;` as being in error.

Given that MySQL is (still) hugely popular, I would hazzard a guess that others also encounter this issue when using Ragtime for migrations on MySQL.

I propose that the check be made, either for `--;;` or `-- ;;`, therefore changing the regex from this:

```
(defn- read-sql [file]
  (str/split (slurp file) #"(?m)\n\s*--;;\s*\n"))
```

to this:

```
(defn- read-sql [file]
  (str/split (slurp file) #"(?m)\n\s*--\s?;;\s*\n"))
```

This would ensure continued behaviour for existing users (and those not using MySQL), but permit those using MySQL to use `-- ;;` (with a single space) as the separator (and therefore keep the MySQL parser happy...)

I would be happy to submit a PR if this is consideration is accepted.

Thank you.

-=david=-

**Comment by weavejester** [comment]
This seems a very sensible change, and I'd welcome a PR.

**Comment by dharrigan** [comment]
PR ready :-)
