### ISSUE TITLE
Statement execution breaks when creating stored procedures

### ISSUE THREAD

**Issue by ckuttruff** [weavejester/ragtime#17]
In cases where you want to create a stored procedure (temporarily changing the delimiter), the method used to split sql strings in the following function breaks execution:
https://github.com/weavejester/ragtime/blob/master/ragtime.sql.files/src/ragtime/sql/files.clj#L51

Looking into a possible fix right now (perhaps utilizing jdbc's batch statement execution directly); might take me a bit as I'm new to clojure/leiningen; just wanted to post this issue here in the meantime.

Example sql statement:
```sql
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
        BEGIN
                RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

**Comment by weavejester** [comment]
Should be fixed by version 0.4.0 redesign.
