### ISSUE TITLE
Migrate Required before rollback.

### ISSUE THREAD

**Issue by debetimi** [weavejester/ragtime#37]
Currently it seems that you have to migrate before your rollback in the same JVM session.  This is because of the use of the "defined-migration" atom, which stores applied migrations, and then filters the applied migrations returned from the Migratable. 
The culprit is the function "applied-migrations".  Perhaps I'm missing something but I don't see the utility in this.  If the Migratable interface returns applied migrations what is the purpose of filtering again on an in memory map?  It seems like an odd choice considering any relevant info should come from a database.

**Comment by weavejester** [comment]
Should be fixed by version 0.4.0 redesign.
