### ISSUE TITLE
How to deal with production env

### ISSUE THREAD

**Issue by iwinux** [weavejester/ragtime#39]
Obviously, to run `lein ragtime migrate` I have to install leiningen on production server. Is it the recommended way? Or call ragtime programmatically as suggested by #13?

**Comment by elrob** [comment]
We are trying to use `java -cp uberjar.jar ragtime.main migrate` but we just get the error "Error: Could not find or load main class ragtime.main". Any idea what we might be doing wrong?

**Comment by shanmuha** [comment]
I am getting the same error as well when running `java -cp uberjar.jar ragtime.main migrate`

**Comment by LukasRychtecky** [comment]
IMO you can try https://github.com/weavejester/ragtime/wiki/Leiningen-Integration. If you environment doesn't have `lein` command then you can pass a parameter to the main functions and run it from the main.
