### ISSUE TITLE
Ragtime silenty fails when migrating sql files containing apostrophe in comment.

### ISSUE THREAD

**Issue by kasz** [weavejester/ragtime#40]
If migration SQL file contains character ' in comments migration looks like performed sucessfully (ragtime_migrations table is updated) but migration is not performed. 
Observed this bug on PostgreSQL, using ragtime 0.3.6. I don't know if it occurs on other DBMSes.

**Comment by weavejester** [comment]
Should be fixed by version 0.4.0 redesign.
