### ISSUE TITLE
Allow SQL migrations to take multiple commands

### ISSUE THREAD

**Issue by weavejester** [weavejester/ragtime#69]
Some SQL databases won't allow certain combinations of SQL to be sent in the same command, and separating SQL statements in a cross-platform way turns out to be an intractable problem. Therefore the format for migrations will be changed to make the commands explicit, via edn:

```clojure
{:up   ["CREATE TABLE foo (id int)"]
 :down ["DROP TABLE foo"]}
```

**edit**: SQL migrations will also support the format outlined by @ragnard, i.e.

    <id>.up.<n>.sql
    <id>.down.<n>.sql

And the old SQL format:

    <id>.up.sql
    <id>.down.sql

See issues #40, #38 and #17.

**Comment by ragnard** [comment]
I think having the migrations be plain SQL files is very valuable. It means I can open them in my editor, edit the contents in the best way my editor can provide, get syntax highlightning, helpful formattting, maybe completion when connected to a database, execute statements line-by-line REPL style, etc. As soon as we stuff SQL text in a string we lose all that.

Have you considered the option of allowing multiple files per up/down migration, executed as separate commands in order by some sequence identifier? For example:

```
20120903221323-add-test-table.up.1.sql
20120903221323-add-test-table.up.2.sql
20120903221323-add-test-table.up.3.sql
```

**Comment by weavejester** [comment]
That's an interesting suggestion. Perhaps the syntax can be determined from the filename. So:

* `\.edn$`
* `\.(up|down)\.sql$`
* `\.(up|down)\.\d+\.sql$`

The reason I might still keep the edn syntax is that it's more concise and needs little code. Additionally, if a multimethod is used based on the file extension, other formats can be supported.

**Comment by ragnard** [comment]
I'm all for supporting different formats, I appreciate my views are biased by my particular workflow etc so having this open to extension (with EDN and sql in the box) would be great.

Not exactly sure what the extension point would look like. Might be a challenge to just dispatch on extension as the SQL format with multiple files per migration would need to consider a set of files and order them. But I don't know how the logic for loading files currently looks like.

**Comment by weavejester** [comment]
We just take a list of files, group them by extension, and then send each group to a multimethod.

**Comment by timvisher** [comment]
I generally stick to one statement per file and just use the normal sequencing method to get this behavior. What's the intrinsic value in providing multiple statements in a file?

**Comment by weavejester** [comment]
Grouping statements allows the migration to be considered atomically. If one statement fails, the whole migration fails.

**Comment by timvisher** [comment]
Ah. Yeah that makes sense. I guess I haven't been doing much DML with ragtime yet. That use case wasn't in my head.

**Comment by weavejester** [comment]
Done (99edc4c0).
