### ISSUE TITLE
feature request for mutiple migrations per file

### ISSUE THREAD

**Issue by yogthos** [weavejester/ragtime#75]
The current recommended approach is to split up each command in its own separate file. This can result in large amounts of files for each migration for many non-trivial cases. This incurs an overhead on the users having to manage multiple files with related commands, and can make it harder to see the entirety of the migration being applied.

The rationale behind this [appears to be](https://github.com/weavejester/ragtime/wiki/SQL-Migrations#sql) that using a heuristic to determine the split between commands is error prone. I agree with that, and my suggestion would be to prove an ability to use an optional separator token the way Yesql and Migratus do.

For example, Migratus uses `--;;` user supplied tokens to split multiple migration commands in the same file. This removes the ambiguity of having to infer the split between the commands without necessitating the use of a file per command.

The feature could be entirely optional and the token could be a key in the config map, so if its not present then the default behavior would not be affected.

**Comment by michaelklishin** [comment]
Does ActiveRecord allow multiple migrations per file? I'd rather learn what from what has been working for them for a decade than trying to accommodate such edge cases.

**Comment by yogthos** [comment]
ActiveRecord is closer to Lobos as it's a DSL, so not sure if the comparison really makes sense as it's already as abstraction over SQL. It does support this workflow however as seen [here](https://programmers.stackexchange.com/questions/165564/is-it-bad-form-to-change-multiple-tables-in-a-single-rails-migration-file). The link also makes the same point that it's desirable to keep related changes in a single file.

The key point that I want to reiterate is that it would be opt-in functionality. The user would have to explicitly specify the delimiter and actively use it. There's no regression in the base case.

**Comment by weavejester** [comment]
This sounds like a reasonable feature to add. It doesn't affect any existing syntax, and would be more convenient in certain situations. I'm fine with re-using the syntax in Migratus.

**Comment by yogthos** [comment]
Fantastic!
