### ISSUE TITLE
Add function to core that migrates like repl

### ISSUE THREAD

**Issue by virmundi** [weavejester/ragtime#78]
The repl version of migration takes a DataStore and a sequence of Migration. The core version requires index, which is not clear as to what it does. The repl verison provides a default implementation of this missing thing. 
Could you add a similar version to core as repl?

**Comment by weavejester** [comment]
The index is explained briefly in the docstring and in more detail in the [concepts](https://github.com/weavejester/ragtime/wiki/Concepts#indexes) wiki page.

`ragtime.core` is a namespace built around simplicity, whereas `ragtime.repl` is a namespace built around convenience. The repl namespace can "cheat" for the sake of convenience, and provide an index based off what has already been migrated, which works *most* of the time.

However, the index isn't hard to add manually:

```clojure
(ragtime/migrate-all db {} migrations)
(ragtime/rollback-last db (ragtime/into-index migrations))
```

It's possible that the index could be defaulted to `{}` in the case of `migrate-all`, however it's a necessary argument for `rollback-last` and `rollback-to`.
