### ISSUE TITLE
Add a new arity to logging-reporter to include the DataStore

### ISSUE THREAD

**Issue by danielcompton** [weavejester/ragtime#86]
The logging-reporter only receives the name of the migration and the operation. This means that if I want to run migrations in parallel across many databases, the migrations logs would be mixed up between databases with no way of correlating which database a log message applies to. What are your thoughts about passing in the DataStore or some other database identifier to be used for logging purposes?

**Comment by weavejester** [comment]
I think that's a reasonable idea. Perhaps make the store the first argument to the reporter, so it goes `[store op id]`. People that don't need that data can ignore the argument.
