### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by codahale** [weavejester/ragtime#87]
Databases like Postgres support wrapping most DDL statements inside transactions. That would allow for transactional application of migrations, which among other things would reduce the hassle associated with initially writing and testing migrations.

**Comment by danielcompton** [comment]
@codahale just to confirm, you're talking about running multiple different migrations inside a single transaction?

**Comment by codahale** [comment]
Sorry if I wasn't clear; I meant running all of the statements of a individual migration in a single, per-migration transaction.

I think it should be as simple as wrapping [execute-sql!](https://github.com/weavejester/ragtime/blob/master/ragtime.jdbc/src/ragtime/jdbc.clj#L61) in a transaction, but it's possible some databases which don't support transactional DDL may throw an exception.

**Comment by danielcompton** [comment]
Is it possible to do this already with the current SQL migration support? I'm guessing this is the kind of thing you've already tried, but it doesn't work because each command was sent separately?:

```
{:up   ["BEGIN"
        "CREATE TABLE foo (name VARCHAR(100))"
        "INSERT INTO foo VALUES ('alice'), ('bob')"
        "COMMIT"]
 :down ["DROP TABLE foo"]}
```

**Comment by codahale** [comment]
I actually hadn't thought of that, but I can run transactional DDLs inside migration statements. Thanks for pointing that out; that totally solves my problem. I'll go ahead and close the issue.
