### ISSUE TITLE
Triggers are parsed as prepared statements lacking parameter.

### ISSUE THREAD

**Issue by dpassen1** [weavejester/ragtime#90]
For example,
```sql
CREATE TRIGGER TRG_FOO_BIER
BEFORE INSERT ON FOO
FOR EACH ROW
BEGIN
  SELECT FOO_SEQ.NEXTVAL
  INTO :new.id FROM DUAL
END​
```
yields:
```shell
SQLException Missing IN or OUT parameter at index:: 1  oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow (OraclePreparedStatement.java:1821​)
```

**Comment by weavejester** [comment]
Ragtime uses JDBC and the `clojure.java.jdbc/execute!` function, so it sounds like you're running into some problem with that. If you can suggest a better way of running migrations, I can certainly consider it, but other than that I don't know how to solve this.

**Comment by dpassen1** [comment]
Looks like this was my error, this statement requires a semicolon after the 'END'. Please feel free to close.
