### ISSUE TITLE
jdbc: pattern broken in windows

### ISSUE THREAD

**Issue by sveri** [weavejester/ragtime#91]
Hi,

I just figured out that this line:(re-pattern (str "([^\\" File/separator "]*)\\" File/separator "?$"))
in https://github.com/weavejester/ragtime/blob/master/ragtime.jdbc/src/ragtime/jdbc.clj#L83

On windows File/separator returns "\\" which lets this function break with this exception:

    foo.bar.user=> (re-pattern (str "([^\\]*)\\?$"))
    PatternSyntaxException Unclosed character class near index 9
    ([^\]*)\?$
             ^  java.util.regex.Pattern.error (Pattern.java:1955)

I am not sure what you need this for, so I cannot provide a fix for now I guess. But I could test a snapshot or a fix if you want me to and have no access to windows.

Thanks,
Sven

**Comment by weavejester** [comment]
The code sample you give is different from the line of code that you've linked.

The linked code seems to work fine at the REPL.

```clojure
user=> (let [sep "\\"] (re-pattern (str "([^\\" sep "]*)\\" sep "?$")))
#"([^\\]*)\\?$"
```

Could you post the error you're encountering?

**Comment by sveri** [comment]
Hm, I copy / pasted this one from my windows repl. Are you on linux?

I encountered this one while I tried to use joplin 0.3.4 and migrate something. I throws the same error.

**Comment by weavejester** [comment]
You pasted a REPL session, but the code you posted isn't the same as the code in Ragtime.

**Comment by sveri** [comment]
You are right, it was not exactly the same code, but what I thought comes out after the replacement.
This is the repl session I have without diving into the code:

    C:\Users\sveri\IdeaProjects\temp\closp_showc>lein repl
    2015-12-12 20:13:29.767:INFO::main: Logging initialized @4794ms
    WARNING: update already refers to: #'clojure.core/update in namespace: hara.common.state, being     replaced by: #'hara.common.state/update
    WARNING: update already refers to: #'clojure.core/update in namespace: foo.bar.db.user, being     replaced by: #'korma.core/update
    nREPL server started on port 58457 on host 127.0.0.1 - nrepl://127.0.0.1:58457
    REPL-y 0.3.7, nREPL 0.2.7
    Clojure 1.7.0
    Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
        Exit: Control+D or (exit) or (quit)
     Results: Stored in vars *1, *2, *3, an exception in *e
    
    foo.bar.user=> (require 'foo.bar.db.joplin-alias)
    nil
    foo.bar.user=> (foo.bar.db.joplin-alias/migrate "joplin.edn" :sqlite-dev-env)
    CompilerException java.util.regex.PatternSyntaxException: Unclosed character class near index 9
    ([^\]*)\?$
             ^, compiling:(ragtime/jdbc.clj:83:1)

What I am doing is to call a joplin function that indirectly calls this ragtime function.

**Comment by weavejester** [comment]
Which version of Ragtime are you using?

**Comment by sveri** [comment]
According to https://clojars.org/joplin.jdbc this is version: ragtime/ragtime.jdbc 0.5.1

**Comment by weavejester** [comment]
In which case you're probably running into #83. That's fixed in 0.5.2.

**Comment by sveri** [comment]
Yes, thats true. Sorry for the double issue. I didn't see that one. Upgrade to 0.5.2 fixes the problem. Thanks for your work :-)

**Comment by weavejester** [comment]
No problem. Marking this as closed.
