### ISSUE TITLE
Using SELECT  and side-effect functions in a migration

### ISSUE THREAD

**Issue by atstp** [weavejester/ragtime#92]
I'm using Ragtime for some postgres/postgis migrations, and it's been great so far!

[the postgis docs](http://postgis.net/docs/using_postgis_dbmanagement.html#Create_Spatial_Table) suggest using `SELECT some_function` to add a spatial column, but trying to run a migration like this 

    CREATE TABLE parks (
      park_id    INTEGER,
      park_name  VARCHAR,
      park_date  DATE,
      park_type  VARCHAR
    );
    SELECT AddGeometryColumn('parks', 'park_geom', 128, 'MULTIPOLYGON', 2 );

(copy/pasted from the PostGIS docs). Turns up an error saying  `A result was returned when none was expected.`, which is understandable; `select`ing during a migration normally wouldn't make much sense.

Is there a workaround for using side-effect functions in migrations?

**Extra (perhaps not-so-useful) info:**

For what it's worth, a shallow dive turned up the [`PERFORM` statement](http://www.postgresql.org/docs/current/static/plpgsql-statements.html#PLPGSQL-STATEMENTS-SQL-NORESULT), which looks specific to PL/PgSQL scripts.  

A weak attempt at combining this with ragtime  

    do $$
        PERFORM AddGeometryColumn('parks', 'park_geom', 128, 'MULTIPOLYGON', 2 );
    $$ LANGUAGE plpgsql;

was (perhaps expectedly) fruitless.

**Comment by weavejester** [comment]
Ragtime uses JDBC and the `clojure.java.jdbc/execute!` function, so any limitations of that are limitations in Ragtime. On the other hand, if you can work out a better command Ragtime should be using, then feel free to suggest it in a patch. :)

**Comment by atstp** [comment]
I'd love to, and look forward to contributing! At the moment, i'm still getting familiar with a healthy chunk of clojure.

In the meantime, is there a way to dodge ragtime's `clojure.java.jdbc/execute!` application of the migrations? It seems like ragtime's pretty opinion-less, which got my hopes up, but it sounds like for this use-case, this isn't gonna happen.  Is that correct?

**Comment by weavejester** [comment]
I don't know of any other function more suitable than `execute!`, so you may be running into a JDBC issue. I don't think it's fixable at Ragtime's level.

**Comment by atstp** [comment]
thanks!

**Comment by frenata** [comment]
In case anyone else wanders into this issue with a similar problem:

We found ourselves needing to do a similar side-effecting thing in a postgres migration and found the following workaround was accepted by `ragtime` / `jdbc/execute`:

```
create temp table foo as (select ...);
```

I don't particularly see any reasonable change to `ragtime`, but I'm hopeful others can benefit from the idea regardless.
