### ISSUE TITLE
about the nil migrations

### ISSUE THREAD

**Issue by Loveflowers** [weavejester/ragtime#93]
I use this 

```clojure
(def config
  {:datastore  (jdbc/sql-database {:connection-uri (make-uri)})
   :migrations (jdbc/load-resources "migrations")})
```

and when I run this

```clojure
(config :migrations)
```

I got the nil seq

**Comment by weavejester** [comment]
What files are in your `resources/migrations` directory?

**Comment by Loveflowers** [comment]
20160104-create-foo-table.up.sql
20160104-create-foo-table.down.sql

**Comment by weavejester** [comment]
I'm afraid I can't reproduce this. Are you using the latest version of Ragtime, and are you certain the files are in `resources/migrations` and not another directory?

**Comment by Loveflowers** [comment]
The question was solved when I use them in the other object.But I can`t catch the cause.

**Comment by weavejester** [comment]
I'm afraid I don't understand. What "other object" do you mean?
