### ISSUE TITLE
I can't up or down single magration

### ISSUE THREAD

**Issue by Loveflowers** [weavejester/ragtime#94]
I do this:

```clojure
(:require  [ragtime.core :as rcore])
.....
(rcore/migrate config 20160104) 
```

or

```clojure
(rcore/rollback config 20160104)
```

And I got the result as follow:
```
java.lang.IllegalArgumentException: No implementation of method: :run-up! of protocol: #'ragtime.protocols/Migration found for class: java.lang.Long
```
or
```
 java.lang.IllegalArgumentException: No implementation of method: :run-down! of protocol: #'ragtime.protocols/Migration found for class: java.lang.Long
```

Must I implement the :run-up! or :run-down! ?

**Comment by weavejester** [comment]
You're supplying the wrong types to the function. The `ragtime.core/migrate` and `ragtime.core/rollback` function expect you to supply a migration, but you're giving it a number instead.

It's important to understand that the functions in `ragtime.core` are low level. Most of the time you'll want to work with the functions in `ragtime.repl` instead. For example:

```clojure
(require 'ragtime.repl)
(ragtime.repl/migrate config)             ;; migrates to the latest version
(ragtime.repl/rollback config "20160104") ;; rollbacks to the supplied id
```

**Comment by Loveflowers** [comment]
Thanks
